#!/usr/bin/env python3
"""Canonical PREOS pipeline state/event contract from the three-repo master plan."""
from __future__ import annotations

CANONICAL_STATES = (
    "UNINITIALIZED", "INGESTING", "INTAKE_BLOCKED", "PLANNING", "PLAN_BLOCKED",
    "PLAN_APPROVAL_REQUIRED", "APPROVED_FOR_IMPLEMENTATION", "IMPLEMENTING",
    "IMPLEMENTATION_BLOCKED", "VERIFYING", "VERIFICATION_BLOCKED",
    "APPROVED_FOR_RELEASE", "RELEASE_BLOCKED", "RELEASED", "OPERATING",
    "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT",
)
STATE_SET = set(CANONICAL_STATES)

CANONICAL_EVENTS = {
    "PROJECT_INITIALIZED", "TASK_ACCEPTED", "TASK_PACKET_ISSUED",
    "IMPLEMENTATION_STARTED", "MEANINGFUL_EDIT_COMPLETE", "TEST_BATCH_COMPLETE",
    "BUILD_COMPLETE", "MIGRATION_PREPARED", "MIGRATION_ATTEMPTED",
    "MIGRATION_VERIFIED", "APPROVAL_REQUIRED", "APPROVAL_RECEIVED",
    "SESSION_INTERRUPTED", "IMPLEMENTATION_COMPLETE",
    "RELEASE_AUTHORISATION_REQUIRED", "RELEASED", "OPERATING", "CHECKPOINT",
    "SOFT_CHECKPOINT", "HARD_CHECKPOINT", "RECOVERY_STARTED",
    "RECOVERY_COMPLETED", "RECOVERY_BLOCKED", "RECOVERY_CONFLICT",
}

_ALLOWED = {
    "UNINITIALIZED": {"INGESTING", "PLANNING", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    "INGESTING": {"INGESTING", "INTAKE_BLOCKED", "PLANNING", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    "INTAKE_BLOCKED": {"INGESTING", "INTAKE_BLOCKED", "PLANNING", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    # PLANNING -> VERIFYING is allowed for governed implementation-free tasks
    # (for example documentation/configuration verification). Code-changing tasks
    # are expected to pass through APPROVED_FOR_IMPLEMENTATION/IMPLEMENTING.
    "PLANNING": {"PLANNING", "PLAN_BLOCKED", "PLAN_APPROVAL_REQUIRED", "APPROVED_FOR_IMPLEMENTATION", "IMPLEMENTING", "VERIFYING", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    "PLAN_BLOCKED": {"PLANNING", "PLAN_BLOCKED", "PLAN_APPROVAL_REQUIRED", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    "PLAN_APPROVAL_REQUIRED": {"PLANNING", "PLAN_BLOCKED", "PLAN_APPROVAL_REQUIRED", "APPROVED_FOR_IMPLEMENTATION", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    "APPROVED_FOR_IMPLEMENTATION": {"APPROVED_FOR_IMPLEMENTATION", "IMPLEMENTING", "IMPLEMENTATION_BLOCKED", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    "IMPLEMENTING": {"IMPLEMENTING", "IMPLEMENTATION_BLOCKED", "VERIFYING", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    "IMPLEMENTATION_BLOCKED": {"IMPLEMENTING", "IMPLEMENTATION_BLOCKED", "VERIFYING", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    "VERIFYING": {"VERIFYING", "VERIFICATION_BLOCKED", "APPROVED_FOR_RELEASE", "RELEASE_BLOCKED", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    "VERIFICATION_BLOCKED": {"VERIFYING", "VERIFICATION_BLOCKED", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    "APPROVED_FOR_RELEASE": {"APPROVED_FOR_RELEASE", "RELEASE_BLOCKED", "RELEASED", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    "RELEASE_BLOCKED": {"VERIFYING", "APPROVED_FOR_RELEASE", "RELEASE_BLOCKED", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    "RELEASED": {"RELEASED", "OPERATING", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    "OPERATING": {"OPERATING", "PLANNING", "NEEDS_RECONCILIATION", "RECOVERY_CONFLICT"},
    "NEEDS_RECONCILIATION": {"NEEDS_RECONCILIATION", "RECOVERY_CONFLICT", "PLANNING", "IMPLEMENTING", "VERIFYING", "RELEASE_BLOCKED", "OPERATING"},
    "RECOVERY_CONFLICT": {"RECOVERY_CONFLICT", "NEEDS_RECONCILIATION"},
}

EVENT_TARGETS = {
    "PROJECT_INITIALIZED": "PLANNING",
    "TASK_ACCEPTED": "PLANNING",
    "TASK_PACKET_ISSUED": "APPROVED_FOR_IMPLEMENTATION",
    "IMPLEMENTATION_STARTED": "IMPLEMENTING",
    "MEANINGFUL_EDIT_COMPLETE": "IMPLEMENTING",
    "TEST_BATCH_COMPLETE": "VERIFYING",
    "BUILD_COMPLETE": "VERIFYING",
    "MIGRATION_PREPARED": "IMPLEMENTING",
    "MIGRATION_ATTEMPTED": "NEEDS_RECONCILIATION",
    "MIGRATION_VERIFIED": "VERIFYING",
    "SESSION_INTERRUPTED": None,
    "IMPLEMENTATION_COMPLETE": "VERIFYING",
    "RELEASE_AUTHORISATION_REQUIRED": "RELEASE_BLOCKED",
    "RELEASED": "RELEASED",
    "OPERATING": "OPERATING",
}


def validate_state(state: str) -> str:
    value = str(state or "")
    if value not in STATE_SET:
        raise ValueError(f"invalid PREOS pipeline state: {value!r}")
    return value


def transition_allowed(previous: str, target: str) -> bool:
    validate_state(previous); validate_state(target)
    return target == previous or target in _ALLOWED[previous]


def require_transition(previous: str, target: str) -> None:
    if not transition_allowed(previous, target):
        raise ValueError(f"invalid PREOS state transition: {previous} -> {target}")


def target_for_event(event: str, previous: str, explicit: str | None = None) -> str:
    validate_event(event)
    target = validate_state(explicit) if explicit else EVENT_TARGETS.get(event, previous)
    if target is None: target = previous
    require_transition(previous, target)
    return target


def validate_event(event: str) -> str:
    if event not in CANONICAL_EVENTS:
        raise ValueError(f"invalid PREOS ledger event type: {event}")
    return event
